### ISSUE TITLE
An example please

### ISSUE THREAD

**Issue by Munawwar** [jordoh/ruzon_compass#1]
Hi. Could you provide a full example on how to get the code working? And what are the parameters to be passed to RuzonCompass.compass() method?
I tried:

``` ruby
require 'rmagick'
require 'ruzon_compass'
img = Magick::ImageList.new('img-1.jpg').first
pixels = img.get_pixels(0,0,img.columns,img.rows)
RuzonCompass.compass(pixels, img.columns, img.rows, [4,4,4,4], [45,90,135,180])
```

but the program crashes.

**Comment by jordoh** [comment]
Hi @Munawwar - I'm sorry to say there's no working example. Progress was abandoned prior to getting everything working.
